<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages;

class CounterGenerated extends \Fusion\FusionPage
{
    #[\Fusion\Attributes\ServerOnly]
    public array $discoveredProps = ['count'];
    use \Fusion\Concerns\IsProceduralPage;
    public function runProceduralCode()
    {
        $count = $this->prop(name: 'count', default: 0)->value();
        $this->expose(add: function () use ($count) {
            $count = $count + 1;
        });
        $this->syncProps(get_defined_vars());
    }
    #[\Fusion\Attributes\Expose]
    public function add()
    {
        return call_user_func($this->actions[__FUNCTION__], ...func_get_args());
    }
}