<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages;

use App\Models\Podcast;
class DynamicPodcastGenerated extends \Fusion\FusionPage
{
    #[\Fusion\Attributes\ServerOnly]
    public array $discoveredProps = ['podcast'];
    use \Fusion\Concerns\IsProceduralPage;
    public function runProceduralCode()
    {
        $podcast = $this->prop(name: 'podcast')->fromRoute(class: Podcast::class)->value();
        $this->syncProps(get_defined_vars());
    }
}