<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Class;

class IndexGenerated extends \Fusion\FusionPage
{
    public string $name;
    public function mount()
    {
        $this->name = strtoupper('Aaron');
    }
}