<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages\Class;

use App\Models\Podcast;
class SearchGenerated extends \Fusion\FusionPage
{
    public string $search = '';
    #[\Fusion\Attributes\IsReadOnly]
    public \Illuminate\Support\Collection $podcasts;
    public function mount()
    {
        $this->podcasts = $this->search ? Podcast::query()->where('title', 'like', "%{$this->search}%")->get() : Podcast::all();
    }
    public function favorite(Podcast $podcast)
    {
        return response()->json($podcast->toggleFavorite());
    }
}